sudo: required
language: generic
services:
  - docker

before_install:
    - docker build -t lerolynn/react-test -f ./client/Dockerfile.dev ./client


script:
    - docker run -e CI=true lerolynn/react-test npm test

after_success:
  - docker build -t lerolynn/multi-client ./client
  - docker build -t lerolynn/multi-nginx ./nginx
  - docker build -t lerolynn/multi-server ./server
  - docker build -t lerolynn/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push lerolynn/multi-client
  - docker push lerolynn/multi-nginx
  - docker push lerolynn/multi-server
  - docker push lerolynn/multi-worker